<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.CodeGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Orleans.Core.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Blueprints.Domain\Blueprints.Domain.csproj" />
  </ItemGroup>
</Project>
