<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Finbuckle.MultiTenant.AspNetCore" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\FluentValidation\FluentValidation.Extensions.MinimalApi\FluentValidation.Extensions.MinimalApi.csproj" />
    <ProjectReference Include="..\Blueprints.Contracts\Blueprints.Contracts.csproj" />
    <ProjectReference Include="..\Blueprints.Core\Blueprints.Core.csproj" />
    <ProjectReference Include="..\Blueprints.Store\Blueprints.Store.csproj" />
    <ProjectReference Include="..\Blueprints.Actors\Blueprints.Actors.csproj" />
    <ProjectReference Include="..\Blueprints.Actors.Abstractions\Blueprints.Actors.Abstractions.csproj" />
    <ProjectReference Include="..\Blueprints.Domain\Blueprints.Domain.csproj" />
    <ProjectReference Include="..\Blueprints.Infrastructure\Blueprints.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Common\FluentResults\Results.Extensions.Api\Results.Extensions.Api.csproj" />
  </ItemGroup>
</Project>
