using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ApiExplorer;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;
using Dilcore.WebApi;

namespace Dilcore.WebApi.Infrastructure.OpenApi;

/// <summary>
///     OpenAPI transformer that adds standard Problem Details responses and schema.
///     Implements both Document and Operation transformers to handle components and operation responses respectively.
/// </summary>
internal sealed class OpenApiProblemDetailsTransformer : IOpenApiDocumentTransformer, IOpenApiOperationTransformer
{
    private const string ProblemDetailsSchemaId = "ProblemDetails";

    public Task TransformAsync(OpenApiDocument document, OpenApiDocumentTransformerContext context, CancellationToken cancellationToken)
    {
        // 1. Register the schema in Components (Document scope)
        EnsureProblemDetailsSchema(document);
        return Task.CompletedTask;
    }

    public Task TransformAsync(OpenApiOperation operation, OpenApiOperationTransformerContext context, CancellationToken cancellationToken)
    {
        // Ensure Responses is initialized to avoid null-forgiving usage
        operation.Responses ??= new OpenApiResponses();

        // 2. Add responses to Operations (Operation scope)
        // Add "default" error response
        if (!operation.Responses.ContainsKey("default"))
        {
            operation.Responses.Add("default", CreateProblemDetailsResponse("Unexpected error occurred."));
        }



        // Check for AllowAnonymous attribute
        var isAnonymous = context.Description.ActionDescriptor.EndpointMetadata
            .OfType<AllowAnonymousAttribute>()
            .Any();

        if (!isAnonymous)
        {
            if (!operation.Responses.ContainsKey("401"))
            {
                operation.Responses.Add("401", CreateProblemDetailsResponse("Unauthorized - Authentication is required."));
            }

            if (!operation.Responses.ContainsKey("403"))
            {
                operation.Responses.Add("403", CreateProblemDetailsResponse("Forbidden - User does not have necessary permissions."));
            }
        }

        return Task.CompletedTask;
    }

    private static void EnsureProblemDetailsSchema(OpenApiDocument document)
    {
        document.Components ??= new OpenApiComponents();
        // Use Dictionary<string, IOpenApiSchema> as per reference requirements in v2
        document.Components.Schemas ??= new Dictionary<string, IOpenApiSchema>();

        if (!document.Components.Schemas.ContainsKey(ProblemDetailsSchemaId))
        {
            document.Components.Schemas[ProblemDetailsSchemaId] = GetProblemDetailsSchema();
        }
    }

    private static OpenApiResponse CreateProblemDetailsResponse(string description)
    {
        return new OpenApiResponse
        {
            Description = description,
            Content = new Dictionary<string, OpenApiMediaType>
            {
                [Constants.ProblemDetails.ContentType] = new()
                {
                    Schema = GetProblemDetailsSchema()
                }
            }
        };
    }

    private static OpenApiSchema GetProblemDetailsSchema()
    {
        return new OpenApiSchema
        {
            Type = JsonSchemaType.Object,
            Properties = new Dictionary<string, IOpenApiSchema>
            {
                [Constants.ProblemDetails.Fields.Type] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "A URI reference that identifies the problem type." },
                [Constants.ProblemDetails.Fields.Title] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "A short, human-readable summary of the problem type." },
                [Constants.ProblemDetails.Fields.Status] = new OpenApiSchema { Type = JsonSchemaType.Integer, Description = "The HTTP status code generated by the origin server for this occurrence of the problem." },
                [Constants.ProblemDetails.Fields.Detail] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "A human-readable explanation specific to this occurrence of the problem." },
                [Constants.ProblemDetails.Fields.Instance] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "A URI reference that identifies the specific occurrence of the problem." },
                [Constants.ProblemDetails.Fields.TraceId] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "The trace ID for the request." },
                [Constants.ProblemDetails.Fields.ErrorCode] = new OpenApiSchema { Type = JsonSchemaType.String, Description = "A specific application error code." },
                [Constants.ProblemDetails.Fields.Timestamp] = new OpenApiSchema { Type = JsonSchemaType.String, Format = "date-time", Description = "The timestamp when the problem occurred in ISO 8601 format." }
            }
        };
    }
}